/**
 * SUPERVYBE - Groups Screen Brain (groups.js)
 * Role: Problem checker, auto-updator, self-healing, self-generator.
 * Integrates: elastic_db_manager.js, communication_bridge.js
 */

document.addEventListener("DOMContentLoaded", () => {
    console.log("🧠 Supervybe Groups Brain Initialized. Running environment checks...");
    
    // 1. Diagnostics & Boot
    runGroupDiagnostics();
    
    // 2. Load Core Group Content
    loadGroups();
    
    // 3. Initialize Interactive Toggles
    initializeGroupInteractions();
    
    // 4. Start Background Self-Healing & Sync Cycle
    startSelfHealingCycle();
});

// --- CORE GENERATOR & DATA LOADER ---

function loadGroups() {
    const groupContainer = document.getElementById('group-list-container');
    if (!groupContainer) return;

    // Check if the Elastic DB Manager is loaded and available
    if (typeof ElasticDBManager !== 'undefined' && ElasticDBManager.fetchGroups) {
        console.log("📡 Pulling live groups from elastic_db_manager.js...");
        ElasticDBManager.fetchGroups(groupContainer);
    } else {
        console.warn("⚠️ ElasticDBManager not detected. Master AI generating fallback community hubs...");
        generateFallbackGroups(groupContainer);
    }
}

function generateFallbackGroups(container) {
    // Only generate if the container is currently empty to prevent infinite stacking
    if (container.children.length > 0) return;

    const autoGeneratedGroups = [
        { icon: '📈', name: 'Gold Traders', desc: 'Market insights & predictions', isAdmin: false, joined: true },
        { icon: '🎮', name: 'Gamers Lounge', desc: 'Tournaments & streaming', isAdmin: false, joined: false },
        { icon: '🚀', name: 'Tech Innovators', desc: 'Boostiful app development ideas', isAdmin: true, joined: true },
        { icon: '🩺', name: 'Health Sentinels', desc: 'Daily body maintenance remedies', isAdmin: false, joined: true }
    ];

    autoGeneratedGroups.forEach(group => {
        const card = document.createElement('div');
        card.className = 'group-card';
        card.innerHTML = `
            <div class="group-info">
                <div class="group-icon">${group.icon}</div>
                <div class="group-details">
                    <h3>${group.name}</h3>
                    <p>${group.desc}</p>
                </div>
            </div>
            <div class="group-actions">
                <button class="btn-icon btn-toggle-join" title="Join/Leave">
                    ${group.joined ? '✔️' : '➕'}
                </button>
                <button class="btn-icon btn-manage ${group.isAdmin ? '' : 'hidden'}" title="Manage Group">⚙️</button>
            </div>
        `;
        container.appendChild(card);
    });
}

// --- INTERACTION LOGIC ---

function initializeGroupInteractions() {
    const groupContainer = document.getElementById('group-list-container');
    if (!groupContainer) return;

    groupContainer.addEventListener('click', (e) => {
        // Handle Join/Leave Toggle
        if (e.target.closest('.btn-toggle-join')) {
            const btn = e.target.closest('.btn-toggle-join');
            const isJoined = btn.textContent.trim() === '✔️';
            
            // Toggle UI state
            btn.textContent = isJoined ? '➕' : '✔️';
            
            // Sync with Comm Bridge if available
            if (typeof CommunicationBridge !== 'undefined' && CommunicationBridge.syncUserStatus) {
                CommunicationBridge.syncUserStatus(isJoined ? 'leave' : 'join');
            } else {
                console.log(`🔄 AI Local Sync: User ${isJoined ? 'left' : 'joined'} group.`);
            }
        }

        // Handle Manage Group Button (Admins only)
        if (e.target.closest('.btn-manage')) {
            console.log("⚙️ Master AI: Routing admin to Moderation Access tools...");
            // In a full app, this might open a modal or redirect
            alert("Moderation Access: Opening Manage Group panel.");
        }
    });
}

// --- SELF-HEALING, UPDATOR & PROBLEM CHECKER ---

function runGroupDiagnostics() {
    let healthScore = 100;
    
    if (!document.getElementById('group-list-container')) {
        console.error("⛔ Problem Checker: group-list-container is missing!");
        healthScore -= 30;
    }
    
    if (typeof CommunicationBridge === 'undefined') {
        console.warn("⚠️ Problem Checker: communication_bridge.js is offline. Running in isolated mode.");
        healthScore -= 10;
    }

    if (healthScore < 100) {
        console.log(`🛠️ Master AI triggering auto-correction. Health: ${healthScore}%`);
        window.triggerGroupHealing();
    } else {
        console.log("✅ Groups Diagnostics Complete. Status: Boostiful.");
    }
}

function startSelfHealingCycle() {
    // Background monitor runs every 15 seconds
    setInterval(() => {
        const container = document.getElementById('group-list-container');
        
        // 1. Self-Generator logic if feed was accidentally wiped
        if (container && container.children.length === 0) {
            console.log("🔄 Self-Healing AI: Hubs vanished. Regenerating group feed...");
            loadGroups();
        }

        // 2. Data Sync Auto-Updator (Pulls pinned posts/polls to sync to Home Screen)
        if (typeof CommunicationBridge !== 'undefined' && CommunicationBridge.pollLatestAnnouncements) {
            CommunicationBridge.pollLatestAnnouncements();
        }
        
    }, 15000);
}

// Global hook for manual/external recovery
window.triggerGroupHealing = function() {
    console.log("⚕️ Groups Master AI: Healing executed. Restoring UI...");
    const main = document.getElementById('supervybe-main-content');
    if (main && !document.getElementById('group-list-container')) {
        const section = document.createElement('section');
        section.id = 'group-list-container';
        section.className = 'group-container';
        main.appendChild(section);
        loadGroups();
    }
};
